### ISSUE TITLE
Suggestion, not an issue.

### ISSUE THREAD

**Issue by Kee7702** [DADi590/PS3-Proxy-Server-for-Android#2]
Since this app is kinda already meant for hacking how PS3 works, is it possible to add a working application update bypass?
Ones I've seen before only delay you getting disconnected from PSN, but is it possible to instead of giving an empty response to replace a0.ww.np.dl.playstation.net with a file saying that the application is on 1.00?
It will take some time to find out what the format of the file is, but it shouldn't be that hard.

**Comment by Kee7702** [comment]
Here's a version file, but I am currently unable to replace it with a local modification.
https://a0.ww.np.dl.playstation.net/tpl/np/NPUB31419/NPUB31419-ver.xml

**Comment by Edw590** [comment]
Hi. There is only a problem that is not possible to solve at the moment... The URL you linked is HTTPS. And I've already tried to redirect HTTPS URLs and that can't be done - not unless you replace a certificate with one of your own and do some stuff I don't remember now (I studied a bit of that specifically for the PS3 and I don't remember all now, but I realized it couldn't be done until someone finds out how to replace SSL CA certificates on 4.XX firmwares, since on 3.XX and older it should be possible).

So I can't really do anything with that XML. If I'm not mistaken, the only thing I can do with an HTTPS URL is to let people SEE only the DOMAIN and nothing else - and the app already does that (shows accessed HTTP complete URLs and HTTPS domains). If I could put a modified CA certificate on the PS3, I could modify HTTPS URLs like that one and mess with some cool stuff (custom What's New, for example, other HEN installers maybe and also more). Ah but now I remember a thing. At that time, I saw it might be possible if I had a server specifically for this and with an SSL CA certificate that the PS3 accepts paid by me which costs some hundreds XD, so..... nope haha.

Unless you know some other way? If the URL were on HTTP there would be no problem at all in doing that - next update (in some years it seems XD) should have an HTTPS to HTTP converter, for example (modifies content on HTTP URLs - but not on HTTPS, no way that I know to do that).

**Comment by Kee7702** [comment]
Can you replace http://b0.ww.np.dl.playstation.net, the server for application updates?
I know it's possible, but due to the method, results aren't always the same.

**Comment by Edw590** [comment]
Well, as long as it's HTTP it's possible to do everything with it on the proxy. What would you like me to do with that? On the beggining you said to replace the app XML with one that says the latest version is 1.00 (but that was on a0, at least by what you said), so the app thinks it's updated and just loads up (that's it, right?). So what would you like me to do with b0? (Was now seeing on psdevwiki and they don't say there what b0 does exactly, so not sure.)

**Comment by Kee7702** [comment]
If you look at the first url, you will see either the game name, or the raw code. You may need to use Inspect Element
Here is a pkg file, you'll notice it has b0.ww.np.dl.playstation.net, and is http.
http://b0.ww.np.dl.playstation.net/tppkg/np/NPUB31419/NPUB31419_T95/dbaf89aa2688b83d/UP4433-NPUB31419_00-MINECRAFTPS30295-A0178-V0100-PE.pkg
You would only have to add a hostname redirect feature, and it should work.
It might even work with ps4, given that you know the url for pkg installs.

Also, would you be able to replace it with a file from an application on 1.00?
https://a0.ww.np.dl.playstation.net/tpl/np/NPUA70045/NPUA70045-ver.xml

**Comment by Edw590** [comment]
I thought I had posted here something... Weird. Sorry about that. I'll post now(again?).

I may need months to release a new update of the app... I'm sorry about that. Until August I didn't have time for anything except studying. So for 1.5 months I've been retrieving the time I had not to do some stuff I'd love to. For example, I'm now finally learning exploitation - something that has been in my mind since the beggining of December of last year (wow, almost a year haha - 10.5 months). I may release the app while studying. Quarentine took much time from me. Had to work more to get things done on university (actually, from my home). As soon the holidays started I tried to release an update on HAN Toolbox, since the last version was broken. Next update for it and for the app may take more time... I have many ideas in my head and not enough time for all (maybe that's good - not all at once).

I'll get back to this again some time, hopefully. I have the message as unread on my Gmail account. Few messages are like that and a desktop program reminds me of all of them each hour, so I know I still have this to do. I won't forget about it as long as the message is as unread. This in case you still need and didn't find some alternate solution already?

**Comment by Kee7702** [comment]
Is there a alpha or beta version of this application available? If you aren't finished with the update, but you have something finished, you could upload an actual pre-release.

**Comment by Edw590** [comment]
Sorry, I've been "a bit" busy haha. I don't have Git set up for this project (nor any project haha, as I don't know how to work with that, yet). I'd like to publish a project of mine which is an assistant, which partially controls my phone since I broke its screen and touch glass, so I can only control it with its 3 buttons and with my voice (and I refuse to buy a new one because this way I can continue to develop the assistant haha - at least when I have time, which has been never for the past month).

But I'll put the ZIP here, in case you or anyone would like to have a look on it. Though, I can't guarantee it's working or something, as I don't touch on this thing since [gonna check... hahaha] January 9th 2020 [wow, almost an year]. Also.... my feelings if you're gonna try to understand the code, because that was before I even knew what an object and a class were hahahahaha. Now I know better what they are, so hopefully my assistant app is being better coded than this thing, which I'll have to check and update all the code before I publish another version... The code must be awful xD.

[PS3ProxyServerforAndroid.zip](https://github.com/DADi590/PS3-Proxy-Server-for-Android/files/5578734/PS3ProxyServerforAndroid.zip)

**EDIT:** Just opened this back, so I'm more sure I won't forget about it. I've been trying to cleanup the "code" a bit ("code" because that was anything but code xD, and maybe will keep not being completely what you call code hahahaha - not enough time to rewrite it from 0, which I should but won't do....)

**Comment by Kee7702** [comment]
1. I believe that if you just host a https server where the 404 pages are entirely blank, it'll probably work to get past updates.
2. You still haven't removed the warning from the app, which gives you a update notification.

**Comment by Edw590** [comment]
Hi. I've been without time. Been studying. And my amazing vacations which I just learned I have up to the 28th and not to some 31th (forgot it's February, and to get it worse, this year ends on the 28th), so vacations are almost null. Cool. Never mind. You may close it if you feel like so. I'll only have time in my Summer holidays to do anything with this (August). Not before. Damn studies which I love, but I hate the 0 time. WTF.

1 - Sorry, can't host any site (at least publicly), while I don't read enough to know about security on that part.
2 - I really thought I had removed that warning 2 months ago. Checked now. Put the what was supposed on the TXT file, but didn't delete the warning from it (fixed partially). Thank you. Now I think it should have been removed.

If you find some way to do it through updating the app code, you may do it and if it works, I may publish an updated version with what you put here or something (if I find time, but shouldn't be that time taking, I guess). But won't be me.... Had various things I wanted to do in my "1 week" vacations - they're only 4 days and 2 are lost with me tired, so nope 😄.
